### ISSUE TITLE
Feature Request (Seed Channels)

### ISSUE THREAD

**Issue by swiftymarks** [sendbird/sendbird-ios-framework#16]
Hello, can you guys able to add a seed contents for the SBDGroupChannel so we can make test on our app. Since the class is marked as final we can't subclass it on our own to make that function. Nor modify some properties since it's marked as Get only

**Comment by famous90** [comment]
Sorry to reply late. You can test with our sample application ID. In AppDelegate of SendBird-iOS sample, you can find [sample application ID](https://github.com/smilefam/SendBird-iOS/blob/master/sample-objc/SendBird-iOS/AppDelegate.m). 
If you mean providing in your application only, I'm afraid we can't.
