### ISSUE TITLE
push notification not recived

### ISSUE THREAD

**Issue by karuppasamypandian0856** [sendbird/sendbird-ios-framework#17]
I followed below steps from my side but didnot call `didReceiveRemoteNotification` delegate

here APNS configurations done in settings on account
capabilities enabled/device token registration done in xcode
but uploaded certificate was Production here i tried in development 

```
[SBDMain registerDevicePushToken:(.....){
"i got SBDPushTokenRegistrationStatusSuccess"
}];
```

**Comment by sf-craig-park** [comment]
Hi, this is Craig.
Thank you for using SendBird for your application!

Could you please share us following informations:
- iOS SDK Version you're working with
- SendBird App ID. You can get the ID in our dashboard, looks like `XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX`
- a device token that you tried to register to our server
- if you got any error message when register the device token. (Does the code you pasted mean that you haved succeeded in registering device token without error?)

If you mind to share it here, please send it to me craig.park@sendbird.com

And could you please check out that if the recipient user is offline throughout all devices since we do not send push notification if a user is online on other platform, including Android, web or sometimes simulator.

Thank you!

**Comment by karuppasamypandian0856** [comment]
Hi @sf-craig-park ,

Q:  iOS SDK Version you're working with
-- i have worked with v3.0
Q:  SendBird App ID. You can get the ID in our dashboard, looks like XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
-- USED APP ID E11F671D-7219-4CDE-B546-9D26A2C20275
Q : a device token that you tried to register to our server
-- Device token: 989b40436e7673a6face3163b9d087c6531c95889158b9a0d51726697467dd14
Q: if you got any error message when register the device token. (Does the code you pasted mean that you haved succeeded in registering device token without error?)
-- yes,No error messages first time not its in pending then second time updating correctly.
Here tried with simulator and one device both users are online.but i cant get notifications.

**Comment by karuppasamypandian0856** [comment]
any update regarding this ?

**Comment by SandeepAggarwal** [comment]
When this issue will get fixed?

**Comment by metpb** [comment]
@sf-jed-kyung Hi, I too am facing a similar issue with notifications. 

FYI the account isn't premium, yet.

I have uploaded the APNS cert (development) as per the docs and successfully registered the device push token with SendBird.  But I somehow am not getting notifications even if the user is offline. Any amount of help would be appreciated. Thanks

**Comment by sf-craig-park** [comment]
@SandeepAggarwal @metpb Hi
Recently, we removed a logic validating a type of certificate uploaded to our server, which is either Development SSL Certificate / Production SSL Certificate.
The certificate you uploaded in our dashboard will be working as APNS type you selected.

![_2017-08-02_ _10_26_31](https://user-images.githubusercontent.com/20384972/28886141-3b590ef8-776d-11e7-8723-4077ac266b55.png)

And I suggest you test your certificate with [Pusher](https://github.com/noodlewerk/NWPusher)
 by sending any push notification to your device. (You can download an application for macOS [here](https://github.com/noodlewerk/NWPusher/releases/latest))

And then, after you found that your certificate works with Pusher, could you please check that the user if offline throughout all devices?
Especially on development stage, a user remains online on a simulator and it bothers to receive push notification.

We wrote some helpful steps about [Why am I not receiving push notifications?](https://help.sendbird.com/hc/en-us/articles/115002331048-Why-am-I-not-receiving-push-notifications-?_ga=2.265341455.1687040223.1501545358-769939232.1470717103)

Hope this help you to receive push notification.

**Comment by famous90** [comment]
@karuppasamypandian0856 Have you resolved this issue? If not, I can help you ASAP

**Comment by evgzor** [comment]
Hi I have a similar issue, however, I got a local notification in ios notification center but I cannot get it in AppDelegate with didReceiveRemoteNotification function. Could u help me with that?

**Comment by famous90** [comment]
hi @evgzor I think you may miss some settings or a method in appDelegate. If not, let me know your environment for push and app settings related with sendbird. 
And [our help center](https://help.sendbird.com/hc/en-us) is more helpful.

**Comment by evgzor** [comment]
I use iOS 11. And to for getting push payload should contain "content-available": 1 otherwise it does not catch in didReceiveRemoteNotification function. sendbird does not generate such payload.

**Comment by famous90** [comment]
@evgzor Following the apple guideline, "content-available" field used for background update. We support all environment(not only background), we recommend that you set this field in your dashboard.
And thanks to your idea, we will discuss containing this field by default.

**Comment by ColinCammaranoAccolade** [comment]
Have there been any updates on this issue? We're also experiencing the same problem. Since the notification payload from SendBird doesn't seem to include `"content-available" : 1`, the application will not call `application(_:didReceiveRemoteNotification:fetchCompletionHandler:)` unless the user taps on the banner.

**Comment by davidgdoll** [comment]
To enable content-available or mutable-content, you have to user the platform API: https://docs.sendbird.com/platform/application#3_add_an_apns_push_configuration

Use that endpoint to upload the certificate and set content_available to true.

**Comment by adamteale** [comment]
Hey @davidgdoll I can't seem to find where to set content-available in the dashboard.
Is it in Settings -> Notifications ?

**Comment by davidgdoll** [comment]
@adamteale It is not available through dashboard, you have yo use the platform API to set your push configurations, see the link: 
https://docs.sendbird.com/platform/application#3_add_an_apns_push_configuration

**Comment by adamteale** [comment]
Thanks for letting me know!

**Comment by martinklimek** [comment]
I've followed your instruction @davidgdoll and I'm able to receive PN callback in the code - thanks for this info. The issue I have now is that all push notifications are doubled. One is coming based on template in the Dashboard and another one from the callback formatted by me in the app. 

Any idea how can I fix this and remove template based on?

**Comment by intoxicated** [comment]
Since it seems like OP is resolved, I'm closing the thread.
