### ISSUE TITLE
Swift Compiler Warning

### ISSUE THREAD

**Issue by drwin** [sendbird/sendbird-ios-framework#23]
![image](https://user-images.githubusercontent.com/232649/32869141-c7ef29da-cab8-11e7-9373-2676ba8cc100.png)

![image](https://user-images.githubusercontent.com/232649/32869174-f0ecbd3e-cab8-11e7-839d-9b8457142aa8.png)

Swift compiler warning occurs.

**Comment by famous90** [comment]
Hi @drwin, are you still facing this issue? After update SendBird SDK, you can solve this issue.

**Comment by harishsaini** [comment]
Yes, We are also facing this issue, please help, we are using `3.0.92` version, let us know what we can do to resolve it.

**Comment by intoxicated** [comment]
Close the thread since I do not see the issue in latest version `3.0.176`.
