### ISSUE TITLE
`setCustomTypeFilter:` not found in swift.

### ISSUE THREAD

**Issue by abingeorgev** [sendbird/sendbird-ios-framework#25]
When we try a channellistquery with customtype filter, previously we used the variable "customtype". Right now it's deprecated, and is suggested to use setCustomFilter.

Please check the image associated. The issue is only for the swift version of the framework. I have attached a screenshot of what I get inside SBDGroupChannelListQuery.

How to solve this??
![screen shot 2018-01-16 at 5 53 26 pm](https://user-images.githubusercontent.com/10165436/34989043-fb6958f4-fae6-11e7-98f0-6cfe5b3f687d.png)

**Comment by famous90** [comment]
Hi @abingeorgev. Sorry to reply late. Is this capture header of SendBird SDK? we provide SDK based on objective-C, so it may be converted one by Xcode. I recommend you to use the framework without converting. 
If you want to to query group channel list in Sendbird SDK, use SBDGroupChannelListQueryInstance.setCustomTypesFilter([string, ...]), [SBDGroupChannelListQuery setCustomTypesFilter:] in objective-c.

**Comment by intoxicated** [comment]
Please use `customTypesFilter` (array) instead. Thanks
