### ISSUE TITLE
there is some case when SBDUserMessage data is null

### ISSUE THREAD

**Issue by ichina** [sendbird/sendbird-ios-framework#30]
swift version:
1. got some `var msg: SBDUserMessage`
2. trying print in debugger `po msg` 
    - got `0x6080002c03f0 - Message: facebook.com, ID: 1604828586, Sender: Admin The Great, Timestamp: 1528108538395` - everything ok
3. trying print in debugger `po msg.data` 
    - got `-[__NSFrozenDictionaryM length]: unrecognized selector sent to instance 0x60000042cdc0
error: warning: couldn't get required object pointer (substituting NULL): Couldn't load 'self' because its value couldn't be evaluated
`

<img width="915" alt="screen shot 2018-06-04 at 17 14 07" src="https://user-images.githubusercontent.com/1898138/40922464-ea0218d4-681a-11e8-920f-3cee95b63fba.png">

**Comment by ichina** [comment]
Update: the problem is, that in SBDUserMessage `data` property(which is String in swift) i got NSDictionary object(which is possible in obj-c, not in swift), and in Swift there is no possibility to check type of this property

**Comment by omar14** [comment]
We are facing the same issue, did you figure our a solution for this?

**Comment by intoxicated** [comment]
It seems like when we serialize response from server, string like json format may convert to dictionary format instead string. I will keep you guys post when I fix this problem

**Comment by intoxicated** [comment]
@ichina I noticed that on our side DB, data field corresponding to that message is object not a string. Could you provide what payload you sent as data? also in what platform (via SDK or PlatformAPI)
