### ISSUE TITLE
Not getting connected user's read status

### ISSUE THREAD

**Issue by ColinCammaranoAccolade** [sendbird/sendbird-ios-framework#34]
Hi all, is there a way to get the currently connected user's read status per message? I've been trying to debug this for some time, and I can't seem to find a way to get the current user's read status.

Given a group channel with two or more users, where one of the users is the currently connected user, if I call `channel.getReadStatus()`, I get a dictionary with timestamps for the other users, but not the current user. If I call `channel.getReadMembers(for:)` or `channel.getUnreadMembers(with:)`, I get sets that never include the currently authenticated user.

Is there a way for me to get the currently connected user's read status for a given message in a group channel?

I am using `v3.0.114`.

**Comment by intoxicated** [comment]
Hello,  those method you mentioned were updated with boolean option to include all members. Please feel free to reopen the issue if you are still in trouble! Thanks
