### ISSUE TITLE
Setting metaArrayKeys on SBDUserMessageParams

### ISSUE THREAD

**Issue by casey55** [sendbird/sendbird-ios-framework#42]
Trying to test out setting the metaArrayKeys property.  Setting it like so.

```
let params = SBDUserMessageParams(message: message)!
params.metaArrayKeys = ["hello", "bye"]
params.customType = "my message custom type"
		
channel?.sendUserMessage(with: params, completionHandler: { (message, error) in
	//...
})
```

When the user receives this message

message.metaArray is empty
message.customType has the value I set.   "my message custom type"

What is metaArrayKeys used for?  Are we supposed to be able to set it's value?

**Comment by rpekarek** [comment]
We're running into the same issue. Rather than (or in addition to) setting the `metaArrayKeys`, it would be helpful if we could set the `sortedMetaArray` data directly on `SBDBaseMessageParams` prior to sending the message

**Comment by intoxicated** [comment]
Hello, we are going to update regard this issue about late April. Basically, you can set keys and values for `metaArrays` field in param when you send a message.

**Comment by intoxicated** [comment]
@casey55 @rpekarek FYI, we are going to metaArray improvement release at the end of April.
