### ISSUE TITLE
Feature request: Missing callback for markAsRead()

### ISSUE THREAD

**Issue by DonWada** [sendbird/sendbird-ios-framework#49]
I don't see anyway to know if channel.markAsRead() did succeed or not?

There is no callback and if it succeeded, it doesn't trigger the channel delegate `channelDidUpdateReadReceipt(_ sender)`.

Is it possible to add a callback to this function (markAsRead) or extend the `channelDidUpdateReadReceipt` to include it?

We have a UI that depends on the success of markAsRead and so far, there is no way to know this.

**Comment by ferrerod** [comment]
This call has a completion handler with error. Are you not using this?
/**
 *  Marks as read some group channels of the current user.
 *
 *  @param channelUrls The array list with channel urls to be marked as read.
 *  @param completionHandler The handler block to execute.
 */
+ (void)markAsReadWithChannelUrls:(NSArray <NSString *> * _Nonnull)channelUrls
                completionHandler:(nullable void (^)(SBDError *_Nullable error))completionHandler;

**Comment by intoxicated** [comment]
@DonWada Please check our documentation https://docs.sendbird.com/ref/ios/Classes/SBDMain.html#//api/name/markAsReadAllWithCompletionHandler:

**Comment by intoxicated** [comment]
Closed
