### ISSUE TITLE
distribute App then failed

### ISSUE THREAD

**Issue by initialj** [sendbird/sendbird-ios-framework#53]
Failed to verify bitcode in SendBirdSDK.framework/SendBirdSDK:
error: Linker option verification failed for bundle /var/folders/t_/ht08lyv57j3b8tr1sr5dr_yc0000gn/T/SendBirdSDKfzIgRz/SendBirdSDK.armv7.xar (unrecognized arguments: -platform_version iOS 8.0.0 13.0.0)

**Comment by sf-jed-kyung** [comment]
Hello @initialj ,

Can you tell me about the Xcode version and the deployment target of your app?

**Comment by ferrerod** [comment]
This is the same issue we reported here: https://github.com/sendbird/sendbird-ios-framework/issues/52
