### ISSUE TITLE
Thumbnails not generating

### ISSUE THREAD

**Issue by rpekarek** [sendbird/sendbird-ios-framework#54]
We're sending image file messages with the following params:
```
let fileMessageParams = SBDFileMessageParams(file: data)
fileMessageParams?.fileName = "image.jpg"
fileMessageParams?.mimeType = "image/jpeg"
fileMessageParams?.fileSize = UInt(data.count)
let thumbnailSize = SBDThumbnailSize.make(withMaxCGSize: CGSize(width: 320.0, height: 450.0))
fileMessageParams?.thumbnailSizes = [thumbnailSize] as? [SBDThumbnailSize]
```
via `channel.sendFileMessage(with: fileMessageParams...`

But when we retrieve the `SBDFileMessage` later, the `thumbnails` array is empty

**Comment by intoxicated** [comment]
@rpekarek thumbnails is premium feature. Could you confirm that you are eligible to use thumbnail feature?

**Comment by intoxicated** [comment]
We opened thumbnail feature for free users too. Please feel free to reopen if the issue still occurs
