### ISSUE TITLE
Can't build sendbird sample project xcode 11

### ISSUE THREAD

**Issue by Richardson12345** [sendbird/sendbird-ios-framework#55]
![Screen Shot 2019-10-27 at 4 27 53 AM](https://user-images.githubusercontent.com/37545118/67626201-3c1cee80-f872-11e9-8777-822b36c81e13.png)

Can't build sendbird after pod install with with the following errors

**Comment by intoxicated** [comment]
@Richardson12345 can you try to clean build and/or derivedData folder and see if works?
