### ISSUE TITLE
Issues after 3.0.166 release 

### ISSUE THREAD

**Issue by Akshay-bcat** [sendbird/sendbird-ios-framework#60]
2 days ago Sendbird SDK version 3.0.166 and we are facing some serious issues related to SBSMMessageCollectionDelegate  insert event provided in this delegate is not working as expected. Would anyone please provide us any help solving these issues. Following is the brief description about issues with steps to reproduce:

- Open chat module, start any chat conversation, after sending some messages clear chat history. After clearing chat history try sending some messages again. After sending one or two messages you will observe that messages you're typing not reflecting in current ChatView but recipient user will receive those messages. This is happening because at some point, SBSMMessgeCollectionDelegate stops to respond insert event which is responsible for refreshing any newly added message

- Open chat module, open any old conversation which have some messages in it, and clear chat history, in this case Chat history gets cleared but messages present on Current chatView doesn't get cleared due to the same reason explained in last case.

- Sometimes fetch method provided to get available messages gives no response at all. 

- SBSMMessageCollectionDelegate's insert event sometimes return message list with duplicate messages.

I am attaching some videos demonstrating overall issues with Sendbird for iOS, please have a look and let us know  if there is any solution to improve performance of Sendbird Chat functionality.

[SendBird issue .zip](https://github.com/sendbird/sendbird-ios-framework/files/4164804/SendBird.issue.zip)

**Comment by Akshay-bcat** [comment]
After upgrading I downgraded to 3.0.165 but facing same issue in that version too

**Comment by intoxicated** [comment]
@Akshay-bcat Is your issue still reproducible with latest version? (3.0.173)
