### ISSUE TITLE
Issues after 3.0.173 release

### ISSUE THREAD

**Issue by Romulomga** [sendbird/sendbird-ios-framework#62]
Hi,

My app is freezing after send a message.

Im using SendBird SyncManager, and already changed `requestState()` to `sendingStatus` in all over my code.

**Comment by sf-jed-kyung** [comment]
Hi @Romulomga 

Thank you for letting us know. We will look into this issue as soon as possible.

**Comment by sf-jed-kyung** [comment]
Hi @Romulomga 

I have a question. Are you developing your app in Swift?

**Comment by Romulomga** [comment]
Hi @sf-jed-kyung,

My app was originally write in obj c, but recently we start the migration for swift.

Our chat is already in swift, and im using the following sendbird pods: 

>     pod 'SendBirdSDK'
>     pod 'SendBirdSyncManager'

**Comment by sf-jed-kyung** [comment]
Hi @Romulomga 

We've released SyncManager v1.1.19 to solve this issue. Please update it. Thanks!

**Comment by Romulomga** [comment]
Thanks!!
